### ISSUE TITLE
Leonardo Ui through Bower?

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/leonardo-ui#11]
Will Leonardo ever be offered via bower?  We use bower for our front end modules and npm for backend.

**Comment by ricsv** [comment]
@goldbergjeffrey There are no current plans to support Bower. As I understand you can use Github URL:s to install packages. Could this be an option? If so, what would we have to do to support it?

**Comment by goldbergjeffrey** [comment]
We can close this, I am using it through npm fine.
