### ISSUE TITLE
lui-icons not rendering...probably me.

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/leonardo-ui#17]
### Description

lui-icons are not rendering

### Steps to Reproduce

1. Created an angular app
2. in a template added a button with a span tag that contains a class pointing to a cogwheel.
3. render in browser.

##### Expected behavior

cogwheel renders

##### Actual behavior

I get a capital V

### Versions

* Leonardo UI: 1.01
* Browser: Chrome
* Operating system: Windows 2016 
* [Other relevant versions]

### css
```
@font-face {
    font-family: "lui-icons";
    src: url("node_modules/leonardo-ui/dist/lui-icons.woff") format('woff');
}
```

### html
```
<button style="float:right;margin-right:40px;margin-top:20px;" class="lui-button  lui-button--toolbar-inverse" id="config-dialog" ng-click="model.openConfig()"><span class="lui-button__icon  lui-icon  lui-icon--cogwheel" aria-hidden="true"></span></button>
```

Screenshot of result
![image](https://user-images.githubusercontent.com/8709292/26901782-025b6bf8-4ba5-11e7-95f0-122b44a1c0da.png)

**Comment by goldbergjeffrey** [comment]
figured it out.  One issue was that my typing of lui-icons needed to be LUI icons in the font-family declaration and my path needed to point to the files correctly.

**Comment by ricsv** [comment]
Good to know that it was solved!
