### ISSUE TITLE
lui-button--error in documentation should be lui-button--danger

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/leonardo-ui#4]
### Description
Documentation bug
lui-button--error in documentation should be lui-button--danger

### Steps to Reproduce

1. attempt to use lui-button--error styling in a button
2. see that it doesn't color red per docs.

##### Expected behavior

the button would be styled red

##### Actual behavior

the button is styled default

### Versions

* Leonardo UI: 1.0.2
* Browser: Chrome
* Operating system: Win10
* [Other relevant versions]

**Comment by ricsv** [comment]
@goldbergjeffrey Where in the documentation does it say `lui-button--error`?

**Comment by goldbergjeffrey** [comment]
ok, I'm using old documentation.  That said, I can't get this documentation to render in a browser when I download it.  Are there instructions for compiling the leonardo docs from this git?  In addition, looking at Qlik Help the component reference for error is error and not danger so this adds a bit of confusion as well.

![image](https://cloud.githubusercontent.com/assets/8709292/21531608/62bd694a-cd17-11e6-9866-5dc70fecef20.png)

http://help.qlik.com/en-US/sense-developer/3.1/Subsystems/APIs/Content/LeonardoUI/LeonardoUI.htm

**Comment by sbattou** [comment]
@goldbergjeffrey If you go to the "Developing" section in https://github.com/qlik-oss/leonardo-ui/blob/master/CONTRIBUTING.md#developing it explains how you can build the project with the docs

**Comment by ricsv** [comment]
You can also visit the Github pages at https://qlik-oss.github.io/leonardo-ui/ which are running an up-to-date version. A link to these pages will be added to the frontpage of the repo once some changes and cleanup has been done.

@goldbergjeffrey: The documentation you are referring to will be updated in the next version of Sense (where the variant will be `danger` as you say). The docs will show a more clear distinction between "regular" LUI components and Angular directives (right now these two are mixed in the Sense documentation).

**Comment by goldbergjeffrey** [comment]
ok, thanks for the info!
