### ISSUE TITLE
npm run docs does not compile documentation

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/leonardo-ui#5]
### Description

In the contributing.md doc in the developing section, it states to run npm run docs to compile the documentation.  This command returns an error.

https://github.com/qlik-oss/leonardo-ui/blob/master/CONTRIBUTING.md#developing

### Steps to Reproduce

1. enter npm run docs
2. watch the error

![image](https://cloud.githubusercontent.com/assets/8709292/21553486/8086eb3a-cdd6-11e6-8ee5-acee31f91720.png)

##### Expected behavior

docs get compiled

##### Actual behavior

error occurs: 
![image](https://cloud.githubusercontent.com/assets/8709292/21553489/8a1e3c98-cdd6-11e6-82a8-70f24e306f88.png)

### Versions

* Leonardo UI: 1.0.2
* Browser: Chrome
* Operating system: Windows 10 
* [Other relevant versions]

### Resolution

I added `"docs": "node ./tools/build-docs.js"` to the scripts section of the package.json and then ran npm run docs.  All good!

**Comment by ricsv** [comment]
Mentioning the `npm run docs` command should propably be removed from contributing guidelines as it's not really necessary to run to develop. Bit of a history: it was needed recently, now the dev server also rebuilds docs which eliminates the need to run the command when developing.

**Comment by goldbergjeffrey** [comment]
ok, but what if all someone is looking for is the documentation on how to use leonardo ui?  Not to develop, but to use?  Will that end up on qlik help or qlik oss because leonardo is open source?

**Comment by ricsv** [comment]
It depends on if your purpose is:

**To use Leonardo UI in Sense**

In this case, you won't need any getting started material, everything is loaded and ready to use. The qlik help site will contain links to the [Github pages](https://qlik-oss.github.io/leonardo-ui) of this repo which will act as an API reference. The help site will also contain information about usage in Angular.

**To use Leonardo UI without Sense**

In this case, you'd need to read and follow the getting started guide here which describes how to setup standalone usage. Documentation in this repo is about standalone usage and has no reference to Sense.

**Comment by stefanwalther** [comment]
I have added the link to the project, which should also help to find the generated documentation easily: 

![image](https://cloud.githubusercontent.com/assets/669728/21604150/d27e648a-d1a1-11e6-8cce-fb8d7eacd2b0.png)
